### ISSUE TITLE
pypi release has no source upload

### ISSUE THREAD

**Issue by richvdh** [matrix-org/python-unpaddedbase64#4]
https://pypi.org/project/unpaddedbase64/#files shows only wheels, and no source tarball. This is poor karma and apparently breaks BSD portgen (see https://marc.info/?l=openbsd-ports&m=154922733706834&w=2).

While we're there, it would be nice to add a link back to this repo via [project_urls](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls).

**Comment by callahad** [comment]
...happy to tackle this if someone could make me a maintainer for this on PyPI.

I'm https://pypi.org/user/callahad/

**Comment by richvdh** [comment]
@ara4n @Kegsay @erikjohnston @dbkr could one of you do the honours?

I wouldn't mind if you added me (https://pypi.org/user/richvdh/) while you're passing.

**Comment by kegsay** [comment]
@richvdh @callahad done

**Comment by callahad** [comment]
I'll get this fixed

**Comment by callahad** [comment]
https://pypi.org/project/unpaddedbase64/2.0.0/
